# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mtgrimes/dev/TMP-hexgame

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mtgrimes/dev/TMP-hexgame

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mtgrimes/dev/TMP-hexgame/CMakeFiles /home/mtgrimes/dev/TMP-hexgame/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mtgrimes/dev/TMP-hexgame/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named HexGame

# Build rule for target.
HexGame: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HexGame
.PHONY : HexGame

# fast build rule for target.
HexGame/fast:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/build
.PHONY : HexGame/fast

AIPhase.o: AIPhase.cpp.o

.PHONY : AIPhase.o

# target to build an object file
AIPhase.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/AIPhase.cpp.o
.PHONY : AIPhase.cpp.o

AIPhase.i: AIPhase.cpp.i

.PHONY : AIPhase.i

# target to preprocess a source file
AIPhase.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/AIPhase.cpp.i
.PHONY : AIPhase.cpp.i

AIPhase.s: AIPhase.cpp.s

.PHONY : AIPhase.s

# target to generate assembly for a file
AIPhase.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/AIPhase.cpp.s
.PHONY : AIPhase.cpp.s

Actor.o: Actor.cpp.o

.PHONY : Actor.o

# target to build an object file
Actor.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/Actor.cpp.o
.PHONY : Actor.cpp.o

Actor.i: Actor.cpp.i

.PHONY : Actor.i

# target to preprocess a source file
Actor.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/Actor.cpp.i
.PHONY : Actor.cpp.i

Actor.s: Actor.cpp.s

.PHONY : Actor.s

# target to generate assembly for a file
Actor.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/Actor.cpp.s
.PHONY : Actor.cpp.s

AnimatedMesh.o: AnimatedMesh.cpp.o

.PHONY : AnimatedMesh.o

# target to build an object file
AnimatedMesh.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/AnimatedMesh.cpp.o
.PHONY : AnimatedMesh.cpp.o

AnimatedMesh.i: AnimatedMesh.cpp.i

.PHONY : AnimatedMesh.i

# target to preprocess a source file
AnimatedMesh.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/AnimatedMesh.cpp.i
.PHONY : AnimatedMesh.cpp.i

AnimatedMesh.s: AnimatedMesh.cpp.s

.PHONY : AnimatedMesh.s

# target to generate assembly for a file
AnimatedMesh.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/AnimatedMesh.cpp.s
.PHONY : AnimatedMesh.cpp.s

Attack.o: Attack.cpp.o

.PHONY : Attack.o

# target to build an object file
Attack.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/Attack.cpp.o
.PHONY : Attack.cpp.o

Attack.i: Attack.cpp.i

.PHONY : Attack.i

# target to preprocess a source file
Attack.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/Attack.cpp.i
.PHONY : Attack.cpp.i

Attack.s: Attack.cpp.s

.PHONY : Attack.s

# target to generate assembly for a file
Attack.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/Attack.cpp.s
.PHONY : Attack.cpp.s

AttackPhase.o: AttackPhase.cpp.o

.PHONY : AttackPhase.o

# target to build an object file
AttackPhase.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/AttackPhase.cpp.o
.PHONY : AttackPhase.cpp.o

AttackPhase.i: AttackPhase.cpp.i

.PHONY : AttackPhase.i

# target to preprocess a source file
AttackPhase.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/AttackPhase.cpp.i
.PHONY : AttackPhase.cpp.i

AttackPhase.s: AttackPhase.cpp.s

.PHONY : AttackPhase.s

# target to generate assembly for a file
AttackPhase.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/AttackPhase.cpp.s
.PHONY : AttackPhase.cpp.s

CEGUISystem.o: CEGUISystem.cpp.o

.PHONY : CEGUISystem.o

# target to build an object file
CEGUISystem.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/CEGUISystem.cpp.o
.PHONY : CEGUISystem.cpp.o

CEGUISystem.i: CEGUISystem.cpp.i

.PHONY : CEGUISystem.i

# target to preprocess a source file
CEGUISystem.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/CEGUISystem.cpp.i
.PHONY : CEGUISystem.cpp.i

CEGUISystem.s: CEGUISystem.cpp.s

.PHONY : CEGUISystem.s

# target to generate assembly for a file
CEGUISystem.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/CEGUISystem.cpp.s
.PHONY : CEGUISystem.cpp.s

CEGUITextLog.o: CEGUITextLog.cpp.o

.PHONY : CEGUITextLog.o

# target to build an object file
CEGUITextLog.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/CEGUITextLog.cpp.o
.PHONY : CEGUITextLog.cpp.o

CEGUITextLog.i: CEGUITextLog.cpp.i

.PHONY : CEGUITextLog.i

# target to preprocess a source file
CEGUITextLog.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/CEGUITextLog.cpp.i
.PHONY : CEGUITextLog.cpp.i

CEGUITextLog.s: CEGUITextLog.cpp.s

.PHONY : CEGUITextLog.s

# target to generate assembly for a file
CEGUITextLog.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/CEGUITextLog.cpp.s
.PHONY : CEGUITextLog.cpp.s

CGameEngine.o: CGameEngine.cpp.o

.PHONY : CGameEngine.o

# target to build an object file
CGameEngine.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/CGameEngine.cpp.o
.PHONY : CGameEngine.cpp.o

CGameEngine.i: CGameEngine.cpp.i

.PHONY : CGameEngine.i

# target to preprocess a source file
CGameEngine.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/CGameEngine.cpp.i
.PHONY : CGameEngine.cpp.i

CGameEngine.s: CGameEngine.cpp.s

.PHONY : CGameEngine.s

# target to generate assembly for a file
CGameEngine.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/CGameEngine.cpp.s
.PHONY : CGameEngine.cpp.s

CGameState.o: CGameState.cpp.o

.PHONY : CGameState.o

# target to build an object file
CGameState.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/CGameState.cpp.o
.PHONY : CGameState.cpp.o

CGameState.i: CGameState.cpp.i

.PHONY : CGameState.i

# target to preprocess a source file
CGameState.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/CGameState.cpp.i
.PHONY : CGameState.cpp.i

CGameState.s: CGameState.cpp.s

.PHONY : CGameState.s

# target to generate assembly for a file
CGameState.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/CGameState.cpp.s
.PHONY : CGameState.cpp.s

Camera.o: Camera.cpp.o

.PHONY : Camera.o

# target to build an object file
Camera.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/Camera.cpp.o
.PHONY : Camera.cpp.o

Camera.i: Camera.cpp.i

.PHONY : Camera.i

# target to preprocess a source file
Camera.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/Camera.cpp.i
.PHONY : Camera.cpp.i

Camera.s: Camera.cpp.s

.PHONY : Camera.s

# target to generate assembly for a file
Camera.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/Camera.cpp.s
.PHONY : Camera.cpp.s

Character.o: Character.cpp.o

.PHONY : Character.o

# target to build an object file
Character.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/Character.cpp.o
.PHONY : Character.cpp.o

Character.i: Character.cpp.i

.PHONY : Character.i

# target to preprocess a source file
Character.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/Character.cpp.i
.PHONY : Character.cpp.i

Character.s: Character.cpp.s

.PHONY : Character.s

# target to generate assembly for a file
Character.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/Character.cpp.s
.PHONY : Character.cpp.s

CharacterAI.o: CharacterAI.cpp.o

.PHONY : CharacterAI.o

# target to build an object file
CharacterAI.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/CharacterAI.cpp.o
.PHONY : CharacterAI.cpp.o

CharacterAI.i: CharacterAI.cpp.i

.PHONY : CharacterAI.i

# target to preprocess a source file
CharacterAI.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/CharacterAI.cpp.i
.PHONY : CharacterAI.cpp.i

CharacterAI.s: CharacterAI.cpp.s

.PHONY : CharacterAI.s

# target to generate assembly for a file
CharacterAI.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/CharacterAI.cpp.s
.PHONY : CharacterAI.cpp.s

CharacterInfoBox.o: CharacterInfoBox.cpp.o

.PHONY : CharacterInfoBox.o

# target to build an object file
CharacterInfoBox.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/CharacterInfoBox.cpp.o
.PHONY : CharacterInfoBox.cpp.o

CharacterInfoBox.i: CharacterInfoBox.cpp.i

.PHONY : CharacterInfoBox.i

# target to preprocess a source file
CharacterInfoBox.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/CharacterInfoBox.cpp.i
.PHONY : CharacterInfoBox.cpp.i

CharacterInfoBox.s: CharacterInfoBox.cpp.s

.PHONY : CharacterInfoBox.s

# target to generate assembly for a file
CharacterInfoBox.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/CharacterInfoBox.cpp.s
.PHONY : CharacterInfoBox.cpp.s

ConfirmationPrompt.o: ConfirmationPrompt.cpp.o

.PHONY : ConfirmationPrompt.o

# target to build an object file
ConfirmationPrompt.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/ConfirmationPrompt.cpp.o
.PHONY : ConfirmationPrompt.cpp.o

ConfirmationPrompt.i: ConfirmationPrompt.cpp.i

.PHONY : ConfirmationPrompt.i

# target to preprocess a source file
ConfirmationPrompt.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/ConfirmationPrompt.cpp.i
.PHONY : ConfirmationPrompt.cpp.i

ConfirmationPrompt.s: ConfirmationPrompt.cpp.s

.PHONY : ConfirmationPrompt.s

# target to generate assembly for a file
ConfirmationPrompt.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/ConfirmationPrompt.cpp.s
.PHONY : ConfirmationPrompt.cpp.s

Cursor.o: Cursor.cpp.o

.PHONY : Cursor.o

# target to build an object file
Cursor.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/Cursor.cpp.o
.PHONY : Cursor.cpp.o

Cursor.i: Cursor.cpp.i

.PHONY : Cursor.i

# target to preprocess a source file
Cursor.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/Cursor.cpp.i
.PHONY : Cursor.cpp.i

Cursor.s: Cursor.cpp.s

.PHONY : Cursor.s

# target to generate assembly for a file
Cursor.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/Cursor.cpp.s
.PHONY : Cursor.cpp.s

Effect.o: Effect.cpp.o

.PHONY : Effect.o

# target to build an object file
Effect.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/Effect.cpp.o
.PHONY : Effect.cpp.o

Effect.i: Effect.cpp.i

.PHONY : Effect.i

# target to preprocess a source file
Effect.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/Effect.cpp.i
.PHONY : Effect.cpp.i

Effect.s: Effect.cpp.s

.PHONY : Effect.s

# target to generate assembly for a file
Effect.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/Effect.cpp.s
.PHONY : Effect.cpp.s

FBO.o: FBO.cpp.o

.PHONY : FBO.o

# target to build an object file
FBO.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/FBO.cpp.o
.PHONY : FBO.cpp.o

FBO.i: FBO.cpp.i

.PHONY : FBO.i

# target to preprocess a source file
FBO.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/FBO.cpp.i
.PHONY : FBO.cpp.i

FBO.s: FBO.cpp.s

.PHONY : FBO.s

# target to generate assembly for a file
FBO.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/FBO.cpp.s
.PHONY : FBO.cpp.s

FacingPhase.o: FacingPhase.cpp.o

.PHONY : FacingPhase.o

# target to build an object file
FacingPhase.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/FacingPhase.cpp.o
.PHONY : FacingPhase.cpp.o

FacingPhase.i: FacingPhase.cpp.i

.PHONY : FacingPhase.i

# target to preprocess a source file
FacingPhase.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/FacingPhase.cpp.i
.PHONY : FacingPhase.cpp.i

FacingPhase.s: FacingPhase.cpp.s

.PHONY : FacingPhase.s

# target to generate assembly for a file
FacingPhase.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/FacingPhase.cpp.s
.PHONY : FacingPhase.cpp.s

FileLoader.o: FileLoader.cpp.o

.PHONY : FileLoader.o

# target to build an object file
FileLoader.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/FileLoader.cpp.o
.PHONY : FileLoader.cpp.o

FileLoader.i: FileLoader.cpp.i

.PHONY : FileLoader.i

# target to preprocess a source file
FileLoader.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/FileLoader.cpp.i
.PHONY : FileLoader.cpp.i

FileLoader.s: FileLoader.cpp.s

.PHONY : FileLoader.s

# target to generate assembly for a file
FileLoader.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/FileLoader.cpp.s
.PHONY : FileLoader.cpp.s

GLText.o: GLText.cpp.o

.PHONY : GLText.o

# target to build an object file
GLText.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/GLText.cpp.o
.PHONY : GLText.cpp.o

GLText.i: GLText.cpp.i

.PHONY : GLText.i

# target to preprocess a source file
GLText.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/GLText.cpp.i
.PHONY : GLText.cpp.i

GLText.s: GLText.cpp.s

.PHONY : GLText.s

# target to generate assembly for a file
GLText.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/GLText.cpp.s
.PHONY : GLText.cpp.s

GUISystem.o: GUISystem.cpp.o

.PHONY : GUISystem.o

# target to build an object file
GUISystem.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/GUISystem.cpp.o
.PHONY : GUISystem.cpp.o

GUISystem.i: GUISystem.cpp.i

.PHONY : GUISystem.i

# target to preprocess a source file
GUISystem.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/GUISystem.cpp.i
.PHONY : GUISystem.cpp.i

GUISystem.s: GUISystem.cpp.s

.PHONY : GUISystem.s

# target to generate assembly for a file
GUISystem.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/GUISystem.cpp.s
.PHONY : GUISystem.cpp.s

HexGame.o: HexGame.cpp.o

.PHONY : HexGame.o

# target to build an object file
HexGame.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/HexGame.cpp.o
.PHONY : HexGame.cpp.o

HexGame.i: HexGame.cpp.i

.PHONY : HexGame.i

# target to preprocess a source file
HexGame.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/HexGame.cpp.i
.PHONY : HexGame.cpp.i

HexGame.s: HexGame.cpp.s

.PHONY : HexGame.s

# target to generate assembly for a file
HexGame.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/HexGame.cpp.s
.PHONY : HexGame.cpp.s

HexGameEngine.o: HexGameEngine.cpp.o

.PHONY : HexGameEngine.o

# target to build an object file
HexGameEngine.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/HexGameEngine.cpp.o
.PHONY : HexGameEngine.cpp.o

HexGameEngine.i: HexGameEngine.cpp.i

.PHONY : HexGameEngine.i

# target to preprocess a source file
HexGameEngine.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/HexGameEngine.cpp.i
.PHONY : HexGameEngine.cpp.i

HexGameEngine.s: HexGameEngine.cpp.s

.PHONY : HexGameEngine.s

# target to generate assembly for a file
HexGameEngine.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/HexGameEngine.cpp.s
.PHONY : HexGameEngine.cpp.s

HexMap.o: HexMap.cpp.o

.PHONY : HexMap.o

# target to build an object file
HexMap.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/HexMap.cpp.o
.PHONY : HexMap.cpp.o

HexMap.i: HexMap.cpp.i

.PHONY : HexMap.i

# target to preprocess a source file
HexMap.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/HexMap.cpp.i
.PHONY : HexMap.cpp.i

HexMap.s: HexMap.cpp.s

.PHONY : HexMap.s

# target to generate assembly for a file
HexMap.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/HexMap.cpp.s
.PHONY : HexMap.cpp.s

HexTile.o: HexTile.cpp.o

.PHONY : HexTile.o

# target to build an object file
HexTile.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/HexTile.cpp.o
.PHONY : HexTile.cpp.o

HexTile.i: HexTile.cpp.i

.PHONY : HexTile.i

# target to preprocess a source file
HexTile.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/HexTile.cpp.i
.PHONY : HexTile.cpp.i

HexTile.s: HexTile.cpp.s

.PHONY : HexTile.s

# target to generate assembly for a file
HexTile.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/HexTile.cpp.s
.PHONY : HexTile.cpp.s

HexTileMesh.o: HexTileMesh.cpp.o

.PHONY : HexTileMesh.o

# target to build an object file
HexTileMesh.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/HexTileMesh.cpp.o
.PHONY : HexTileMesh.cpp.o

HexTileMesh.i: HexTileMesh.cpp.i

.PHONY : HexTileMesh.i

# target to preprocess a source file
HexTileMesh.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/HexTileMesh.cpp.i
.PHONY : HexTileMesh.cpp.i

HexTileMesh.s: HexTileMesh.cpp.s

.PHONY : HexTileMesh.s

# target to generate assembly for a file
HexTileMesh.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/HexTileMesh.cpp.s
.PHONY : HexTileMesh.cpp.s

HexTileTexture.o: HexTileTexture.cpp.o

.PHONY : HexTileTexture.o

# target to build an object file
HexTileTexture.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/HexTileTexture.cpp.o
.PHONY : HexTileTexture.cpp.o

HexTileTexture.i: HexTileTexture.cpp.i

.PHONY : HexTileTexture.i

# target to preprocess a source file
HexTileTexture.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/HexTileTexture.cpp.i
.PHONY : HexTileTexture.cpp.i

HexTileTexture.s: HexTileTexture.cpp.s

.PHONY : HexTileTexture.s

# target to generate assembly for a file
HexTileTexture.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/HexTileTexture.cpp.s
.PHONY : HexTileTexture.cpp.s

HexUtils.o: HexUtils.cpp.o

.PHONY : HexUtils.o

# target to build an object file
HexUtils.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/HexUtils.cpp.o
.PHONY : HexUtils.cpp.o

HexUtils.i: HexUtils.cpp.i

.PHONY : HexUtils.i

# target to preprocess a source file
HexUtils.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/HexUtils.cpp.i
.PHONY : HexUtils.cpp.i

HexUtils.s: HexUtils.cpp.s

.PHONY : HexUtils.s

# target to generate assembly for a file
HexUtils.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/HexUtils.cpp.s
.PHONY : HexUtils.cpp.s

IdlePhase.o: IdlePhase.cpp.o

.PHONY : IdlePhase.o

# target to build an object file
IdlePhase.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/IdlePhase.cpp.o
.PHONY : IdlePhase.cpp.o

IdlePhase.i: IdlePhase.cpp.i

.PHONY : IdlePhase.i

# target to preprocess a source file
IdlePhase.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/IdlePhase.cpp.i
.PHONY : IdlePhase.cpp.i

IdlePhase.s: IdlePhase.cpp.s

.PHONY : IdlePhase.s

# target to generate assembly for a file
IdlePhase.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/IdlePhase.cpp.s
.PHONY : IdlePhase.cpp.s

Item.o: Item.cpp.o

.PHONY : Item.o

# target to build an object file
Item.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/Item.cpp.o
.PHONY : Item.cpp.o

Item.i: Item.cpp.i

.PHONY : Item.i

# target to preprocess a source file
Item.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/Item.cpp.i
.PHONY : Item.cpp.i

Item.s: Item.cpp.s

.PHONY : Item.s

# target to generate assembly for a file
Item.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/Item.cpp.s
.PHONY : Item.cpp.s

Lighting.o: Lighting.cpp.o

.PHONY : Lighting.o

# target to build an object file
Lighting.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/Lighting.cpp.o
.PHONY : Lighting.cpp.o

Lighting.i: Lighting.cpp.i

.PHONY : Lighting.i

# target to preprocess a source file
Lighting.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/Lighting.cpp.i
.PHONY : Lighting.cpp.i

Lighting.s: Lighting.cpp.s

.PHONY : Lighting.s

# target to generate assembly for a file
Lighting.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/Lighting.cpp.s
.PHONY : Lighting.cpp.s

LightingSetup.o: LightingSetup.cpp.o

.PHONY : LightingSetup.o

# target to build an object file
LightingSetup.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/LightingSetup.cpp.o
.PHONY : LightingSetup.cpp.o

LightingSetup.i: LightingSetup.cpp.i

.PHONY : LightingSetup.i

# target to preprocess a source file
LightingSetup.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/LightingSetup.cpp.i
.PHONY : LightingSetup.cpp.i

LightingSetup.s: LightingSetup.cpp.s

.PHONY : LightingSetup.s

# target to generate assembly for a file
LightingSetup.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/LightingSetup.cpp.s
.PHONY : LightingSetup.cpp.s

LineParser.o: LineParser.cpp.o

.PHONY : LineParser.o

# target to build an object file
LineParser.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/LineParser.cpp.o
.PHONY : LineParser.cpp.o

LineParser.i: LineParser.cpp.i

.PHONY : LineParser.i

# target to preprocess a source file
LineParser.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/LineParser.cpp.i
.PHONY : LineParser.cpp.i

LineParser.s: LineParser.cpp.s

.PHONY : LineParser.s

# target to generate assembly for a file
LineParser.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/LineParser.cpp.s
.PHONY : LineParser.cpp.s

MainGameState.o: MainGameState.cpp.o

.PHONY : MainGameState.o

# target to build an object file
MainGameState.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/MainGameState.cpp.o
.PHONY : MainGameState.cpp.o

MainGameState.i: MainGameState.cpp.i

.PHONY : MainGameState.i

# target to preprocess a source file
MainGameState.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/MainGameState.cpp.i
.PHONY : MainGameState.cpp.i

MainGameState.s: MainGameState.cpp.s

.PHONY : MainGameState.s

# target to generate assembly for a file
MainGameState.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/MainGameState.cpp.s
.PHONY : MainGameState.cpp.s

MainMenuState.o: MainMenuState.cpp.o

.PHONY : MainMenuState.o

# target to build an object file
MainMenuState.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/MainMenuState.cpp.o
.PHONY : MainMenuState.cpp.o

MainMenuState.i: MainMenuState.cpp.i

.PHONY : MainMenuState.i

# target to preprocess a source file
MainMenuState.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/MainMenuState.cpp.i
.PHONY : MainMenuState.cpp.i

MainMenuState.s: MainMenuState.cpp.s

.PHONY : MainMenuState.s

# target to generate assembly for a file
MainMenuState.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/MainMenuState.cpp.s
.PHONY : MainMenuState.cpp.s

MapEditorState.o: MapEditorState.cpp.o

.PHONY : MapEditorState.o

# target to build an object file
MapEditorState.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/MapEditorState.cpp.o
.PHONY : MapEditorState.cpp.o

MapEditorState.i: MapEditorState.cpp.i

.PHONY : MapEditorState.i

# target to preprocess a source file
MapEditorState.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/MapEditorState.cpp.i
.PHONY : MapEditorState.cpp.i

MapEditorState.s: MapEditorState.cpp.s

.PHONY : MapEditorState.s

# target to generate assembly for a file
MapEditorState.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/MapEditorState.cpp.s
.PHONY : MapEditorState.cpp.s

Mesh.o: Mesh.cpp.o

.PHONY : Mesh.o

# target to build an object file
Mesh.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/Mesh.cpp.o
.PHONY : Mesh.cpp.o

Mesh.i: Mesh.cpp.i

.PHONY : Mesh.i

# target to preprocess a source file
Mesh.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/Mesh.cpp.i
.PHONY : Mesh.cpp.i

Mesh.s: Mesh.cpp.s

.PHONY : Mesh.s

# target to generate assembly for a file
Mesh.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/Mesh.cpp.s
.PHONY : Mesh.cpp.s

MovementPhase.o: MovementPhase.cpp.o

.PHONY : MovementPhase.o

# target to build an object file
MovementPhase.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/MovementPhase.cpp.o
.PHONY : MovementPhase.cpp.o

MovementPhase.i: MovementPhase.cpp.i

.PHONY : MovementPhase.i

# target to preprocess a source file
MovementPhase.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/MovementPhase.cpp.i
.PHONY : MovementPhase.cpp.i

MovementPhase.s: MovementPhase.cpp.s

.PHONY : MovementPhase.s

# target to generate assembly for a file
MovementPhase.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/MovementPhase.cpp.s
.PHONY : MovementPhase.cpp.s

Particle.o: Particle.cpp.o

.PHONY : Particle.o

# target to build an object file
Particle.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/Particle.cpp.o
.PHONY : Particle.cpp.o

Particle.i: Particle.cpp.i

.PHONY : Particle.i

# target to preprocess a source file
Particle.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/Particle.cpp.i
.PHONY : Particle.cpp.i

Particle.s: Particle.cpp.s

.PHONY : Particle.s

# target to generate assembly for a file
Particle.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/Particle.cpp.s
.PHONY : Particle.cpp.s

ParticleSystem.o: ParticleSystem.cpp.o

.PHONY : ParticleSystem.o

# target to build an object file
ParticleSystem.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/ParticleSystem.cpp.o
.PHONY : ParticleSystem.cpp.o

ParticleSystem.i: ParticleSystem.cpp.i

.PHONY : ParticleSystem.i

# target to preprocess a source file
ParticleSystem.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/ParticleSystem.cpp.i
.PHONY : ParticleSystem.cpp.i

ParticleSystem.s: ParticleSystem.cpp.s

.PHONY : ParticleSystem.s

# target to generate assembly for a file
ParticleSystem.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/ParticleSystem.cpp.s
.PHONY : ParticleSystem.cpp.s

PickingFBO.o: PickingFBO.cpp.o

.PHONY : PickingFBO.o

# target to build an object file
PickingFBO.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/PickingFBO.cpp.o
.PHONY : PickingFBO.cpp.o

PickingFBO.i: PickingFBO.cpp.i

.PHONY : PickingFBO.i

# target to preprocess a source file
PickingFBO.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/PickingFBO.cpp.i
.PHONY : PickingFBO.cpp.i

PickingFBO.s: PickingFBO.cpp.s

.PHONY : PickingFBO.s

# target to generate assembly for a file
PickingFBO.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/PickingFBO.cpp.s
.PHONY : PickingFBO.cpp.s

Pipeline.o: Pipeline.cpp.o

.PHONY : Pipeline.o

# target to build an object file
Pipeline.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/Pipeline.cpp.o
.PHONY : Pipeline.cpp.o

Pipeline.i: Pipeline.cpp.i

.PHONY : Pipeline.i

# target to preprocess a source file
Pipeline.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/Pipeline.cpp.i
.PHONY : Pipeline.cpp.i

Pipeline.s: Pipeline.cpp.s

.PHONY : Pipeline.s

# target to generate assembly for a file
Pipeline.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/Pipeline.cpp.s
.PHONY : Pipeline.cpp.s

PrintfTextLog.o: PrintfTextLog.cpp.o

.PHONY : PrintfTextLog.o

# target to build an object file
PrintfTextLog.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/PrintfTextLog.cpp.o
.PHONY : PrintfTextLog.cpp.o

PrintfTextLog.i: PrintfTextLog.cpp.i

.PHONY : PrintfTextLog.i

# target to preprocess a source file
PrintfTextLog.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/PrintfTextLog.cpp.i
.PHONY : PrintfTextLog.cpp.i

PrintfTextLog.s: PrintfTextLog.cpp.s

.PHONY : PrintfTextLog.s

# target to generate assembly for a file
PrintfTextLog.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/PrintfTextLog.cpp.s
.PHONY : PrintfTextLog.cpp.s

ResourceManager.o: ResourceManager.cpp.o

.PHONY : ResourceManager.o

# target to build an object file
ResourceManager.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/ResourceManager.cpp.o
.PHONY : ResourceManager.cpp.o

ResourceManager.i: ResourceManager.cpp.i

.PHONY : ResourceManager.i

# target to preprocess a source file
ResourceManager.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/ResourceManager.cpp.i
.PHONY : ResourceManager.cpp.i

ResourceManager.s: ResourceManager.cpp.s

.PHONY : ResourceManager.s

# target to generate assembly for a file
ResourceManager.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/ResourceManager.cpp.s
.PHONY : ResourceManager.cpp.s

ServiceLocator.o: ServiceLocator.cpp.o

.PHONY : ServiceLocator.o

# target to build an object file
ServiceLocator.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/ServiceLocator.cpp.o
.PHONY : ServiceLocator.cpp.o

ServiceLocator.i: ServiceLocator.cpp.i

.PHONY : ServiceLocator.i

# target to preprocess a source file
ServiceLocator.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/ServiceLocator.cpp.i
.PHONY : ServiceLocator.cpp.i

ServiceLocator.s: ServiceLocator.cpp.s

.PHONY : ServiceLocator.s

# target to generate assembly for a file
ServiceLocator.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/ServiceLocator.cpp.s
.PHONY : ServiceLocator.cpp.s

ShaderPipeline.o: ShaderPipeline.cpp.o

.PHONY : ShaderPipeline.o

# target to build an object file
ShaderPipeline.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/ShaderPipeline.cpp.o
.PHONY : ShaderPipeline.cpp.o

ShaderPipeline.i: ShaderPipeline.cpp.i

.PHONY : ShaderPipeline.i

# target to preprocess a source file
ShaderPipeline.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/ShaderPipeline.cpp.i
.PHONY : ShaderPipeline.cpp.i

ShaderPipeline.s: ShaderPipeline.cpp.s

.PHONY : ShaderPipeline.s

# target to generate assembly for a file
ShaderPipeline.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/ShaderPipeline.cpp.s
.PHONY : ShaderPipeline.cpp.s

Technique.o: Technique.cpp.o

.PHONY : Technique.o

# target to build an object file
Technique.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/Technique.cpp.o
.PHONY : Technique.cpp.o

Technique.i: Technique.cpp.i

.PHONY : Technique.i

# target to preprocess a source file
Technique.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/Technique.cpp.i
.PHONY : Technique.cpp.i

Technique.s: Technique.cpp.s

.PHONY : Technique.s

# target to generate assembly for a file
Technique.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/Technique.cpp.s
.PHONY : Technique.cpp.s

TechniqueSelect.o: TechniqueSelect.cpp.o

.PHONY : TechniqueSelect.o

# target to build an object file
TechniqueSelect.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/TechniqueSelect.cpp.o
.PHONY : TechniqueSelect.cpp.o

TechniqueSelect.i: TechniqueSelect.cpp.i

.PHONY : TechniqueSelect.i

# target to preprocess a source file
TechniqueSelect.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/TechniqueSelect.cpp.i
.PHONY : TechniqueSelect.cpp.i

TechniqueSelect.s: TechniqueSelect.cpp.s

.PHONY : TechniqueSelect.s

# target to generate assembly for a file
TechniqueSelect.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/TechniqueSelect.cpp.s
.PHONY : TechniqueSelect.cpp.s

TextLog.o: TextLog.cpp.o

.PHONY : TextLog.o

# target to build an object file
TextLog.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/TextLog.cpp.o
.PHONY : TextLog.cpp.o

TextLog.i: TextLog.cpp.i

.PHONY : TextLog.i

# target to preprocess a source file
TextLog.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/TextLog.cpp.i
.PHONY : TextLog.cpp.i

TextLog.s: TextLog.cpp.s

.PHONY : TextLog.s

# target to generate assembly for a file
TextLog.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/TextLog.cpp.s
.PHONY : TextLog.cpp.s

Texture.o: Texture.cpp.o

.PHONY : Texture.o

# target to build an object file
Texture.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/Texture.cpp.o
.PHONY : Texture.cpp.o

Texture.i: Texture.cpp.i

.PHONY : Texture.i

# target to preprocess a source file
Texture.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/Texture.cpp.i
.PHONY : Texture.cpp.i

Texture.s: Texture.cpp.s

.PHONY : Texture.s

# target to generate assembly for a file
Texture.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/Texture.cpp.s
.PHONY : Texture.cpp.s

Tileset.o: Tileset.cpp.o

.PHONY : Tileset.o

# target to build an object file
Tileset.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/Tileset.cpp.o
.PHONY : Tileset.cpp.o

Tileset.i: Tileset.cpp.i

.PHONY : Tileset.i

# target to preprocess a source file
Tileset.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/Tileset.cpp.i
.PHONY : Tileset.cpp.i

Tileset.s: Tileset.cpp.s

.PHONY : Tileset.s

# target to generate assembly for a file
Tileset.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/Tileset.cpp.s
.PHONY : Tileset.cpp.s

Timer.o: Timer.cpp.o

.PHONY : Timer.o

# target to build an object file
Timer.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/Timer.cpp.o
.PHONY : Timer.cpp.o

Timer.i: Timer.cpp.i

.PHONY : Timer.i

# target to preprocess a source file
Timer.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/Timer.cpp.i
.PHONY : Timer.cpp.i

Timer.s: Timer.cpp.s

.PHONY : Timer.s

# target to generate assembly for a file
Timer.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/Timer.cpp.s
.PHONY : Timer.cpp.s

TurnPhase.o: TurnPhase.cpp.o

.PHONY : TurnPhase.o

# target to build an object file
TurnPhase.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/TurnPhase.cpp.o
.PHONY : TurnPhase.cpp.o

TurnPhase.i: TurnPhase.cpp.i

.PHONY : TurnPhase.i

# target to preprocess a source file
TurnPhase.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/TurnPhase.cpp.i
.PHONY : TurnPhase.cpp.i

TurnPhase.s: TurnPhase.cpp.s

.PHONY : TurnPhase.s

# target to generate assembly for a file
TurnPhase.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/TurnPhase.cpp.s
.PHONY : TurnPhase.cpp.s

Weapon.o: Weapon.cpp.o

.PHONY : Weapon.o

# target to build an object file
Weapon.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/Weapon.cpp.o
.PHONY : Weapon.cpp.o

Weapon.i: Weapon.cpp.i

.PHONY : Weapon.i

# target to preprocess a source file
Weapon.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/Weapon.cpp.i
.PHONY : Weapon.cpp.i

Weapon.s: Weapon.cpp.s

.PHONY : Weapon.s

# target to generate assembly for a file
Weapon.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/Weapon.cpp.s
.PHONY : Weapon.cpp.s

damageEffect.o: damageEffect.cpp.o

.PHONY : damageEffect.o

# target to build an object file
damageEffect.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/damageEffect.cpp.o
.PHONY : damageEffect.cpp.o

damageEffect.i: damageEffect.cpp.i

.PHONY : damageEffect.i

# target to preprocess a source file
damageEffect.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/damageEffect.cpp.i
.PHONY : damageEffect.cpp.i

damageEffect.s: damageEffect.cpp.s

.PHONY : damageEffect.s

# target to generate assembly for a file
damageEffect.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/damageEffect.cpp.s
.PHONY : damageEffect.cpp.s

math_utils.o: math_utils.cpp.o

.PHONY : math_utils.o

# target to build an object file
math_utils.cpp.o:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/math_utils.cpp.o
.PHONY : math_utils.cpp.o

math_utils.i: math_utils.cpp.i

.PHONY : math_utils.i

# target to preprocess a source file
math_utils.cpp.i:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/math_utils.cpp.i
.PHONY : math_utils.cpp.i

math_utils.s: math_utils.cpp.s

.PHONY : math_utils.s

# target to generate assembly for a file
math_utils.cpp.s:
	$(MAKE) -f CMakeFiles/HexGame.dir/build.make CMakeFiles/HexGame.dir/math_utils.cpp.s
.PHONY : math_utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... HexGame"
	@echo "... AIPhase.o"
	@echo "... AIPhase.i"
	@echo "... AIPhase.s"
	@echo "... Actor.o"
	@echo "... Actor.i"
	@echo "... Actor.s"
	@echo "... AnimatedMesh.o"
	@echo "... AnimatedMesh.i"
	@echo "... AnimatedMesh.s"
	@echo "... Attack.o"
	@echo "... Attack.i"
	@echo "... Attack.s"
	@echo "... AttackPhase.o"
	@echo "... AttackPhase.i"
	@echo "... AttackPhase.s"
	@echo "... CEGUISystem.o"
	@echo "... CEGUISystem.i"
	@echo "... CEGUISystem.s"
	@echo "... CEGUITextLog.o"
	@echo "... CEGUITextLog.i"
	@echo "... CEGUITextLog.s"
	@echo "... CGameEngine.o"
	@echo "... CGameEngine.i"
	@echo "... CGameEngine.s"
	@echo "... CGameState.o"
	@echo "... CGameState.i"
	@echo "... CGameState.s"
	@echo "... Camera.o"
	@echo "... Camera.i"
	@echo "... Camera.s"
	@echo "... Character.o"
	@echo "... Character.i"
	@echo "... Character.s"
	@echo "... CharacterAI.o"
	@echo "... CharacterAI.i"
	@echo "... CharacterAI.s"
	@echo "... CharacterInfoBox.o"
	@echo "... CharacterInfoBox.i"
	@echo "... CharacterInfoBox.s"
	@echo "... ConfirmationPrompt.o"
	@echo "... ConfirmationPrompt.i"
	@echo "... ConfirmationPrompt.s"
	@echo "... Cursor.o"
	@echo "... Cursor.i"
	@echo "... Cursor.s"
	@echo "... Effect.o"
	@echo "... Effect.i"
	@echo "... Effect.s"
	@echo "... FBO.o"
	@echo "... FBO.i"
	@echo "... FBO.s"
	@echo "... FacingPhase.o"
	@echo "... FacingPhase.i"
	@echo "... FacingPhase.s"
	@echo "... FileLoader.o"
	@echo "... FileLoader.i"
	@echo "... FileLoader.s"
	@echo "... GLText.o"
	@echo "... GLText.i"
	@echo "... GLText.s"
	@echo "... GUISystem.o"
	@echo "... GUISystem.i"
	@echo "... GUISystem.s"
	@echo "... HexGame.o"
	@echo "... HexGame.i"
	@echo "... HexGame.s"
	@echo "... HexGameEngine.o"
	@echo "... HexGameEngine.i"
	@echo "... HexGameEngine.s"
	@echo "... HexMap.o"
	@echo "... HexMap.i"
	@echo "... HexMap.s"
	@echo "... HexTile.o"
	@echo "... HexTile.i"
	@echo "... HexTile.s"
	@echo "... HexTileMesh.o"
	@echo "... HexTileMesh.i"
	@echo "... HexTileMesh.s"
	@echo "... HexTileTexture.o"
	@echo "... HexTileTexture.i"
	@echo "... HexTileTexture.s"
	@echo "... HexUtils.o"
	@echo "... HexUtils.i"
	@echo "... HexUtils.s"
	@echo "... IdlePhase.o"
	@echo "... IdlePhase.i"
	@echo "... IdlePhase.s"
	@echo "... Item.o"
	@echo "... Item.i"
	@echo "... Item.s"
	@echo "... Lighting.o"
	@echo "... Lighting.i"
	@echo "... Lighting.s"
	@echo "... LightingSetup.o"
	@echo "... LightingSetup.i"
	@echo "... LightingSetup.s"
	@echo "... LineParser.o"
	@echo "... LineParser.i"
	@echo "... LineParser.s"
	@echo "... MainGameState.o"
	@echo "... MainGameState.i"
	@echo "... MainGameState.s"
	@echo "... MainMenuState.o"
	@echo "... MainMenuState.i"
	@echo "... MainMenuState.s"
	@echo "... MapEditorState.o"
	@echo "... MapEditorState.i"
	@echo "... MapEditorState.s"
	@echo "... Mesh.o"
	@echo "... Mesh.i"
	@echo "... Mesh.s"
	@echo "... MovementPhase.o"
	@echo "... MovementPhase.i"
	@echo "... MovementPhase.s"
	@echo "... Particle.o"
	@echo "... Particle.i"
	@echo "... Particle.s"
	@echo "... ParticleSystem.o"
	@echo "... ParticleSystem.i"
	@echo "... ParticleSystem.s"
	@echo "... PickingFBO.o"
	@echo "... PickingFBO.i"
	@echo "... PickingFBO.s"
	@echo "... Pipeline.o"
	@echo "... Pipeline.i"
	@echo "... Pipeline.s"
	@echo "... PrintfTextLog.o"
	@echo "... PrintfTextLog.i"
	@echo "... PrintfTextLog.s"
	@echo "... ResourceManager.o"
	@echo "... ResourceManager.i"
	@echo "... ResourceManager.s"
	@echo "... ServiceLocator.o"
	@echo "... ServiceLocator.i"
	@echo "... ServiceLocator.s"
	@echo "... ShaderPipeline.o"
	@echo "... ShaderPipeline.i"
	@echo "... ShaderPipeline.s"
	@echo "... Technique.o"
	@echo "... Technique.i"
	@echo "... Technique.s"
	@echo "... TechniqueSelect.o"
	@echo "... TechniqueSelect.i"
	@echo "... TechniqueSelect.s"
	@echo "... TextLog.o"
	@echo "... TextLog.i"
	@echo "... TextLog.s"
	@echo "... Texture.o"
	@echo "... Texture.i"
	@echo "... Texture.s"
	@echo "... Tileset.o"
	@echo "... Tileset.i"
	@echo "... Tileset.s"
	@echo "... Timer.o"
	@echo "... Timer.i"
	@echo "... Timer.s"
	@echo "... TurnPhase.o"
	@echo "... TurnPhase.i"
	@echo "... TurnPhase.s"
	@echo "... Weapon.o"
	@echo "... Weapon.i"
	@echo "... Weapon.s"
	@echo "... damageEffect.o"
	@echo "... damageEffect.i"
	@echo "... damageEffect.s"
	@echo "... math_utils.o"
	@echo "... math_utils.i"
	@echo "... math_utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

